### ISSUE TITLE
Adaptation Scenario Comparision

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/scenario-analysis#14]
Read [Adaptation Resources](https://github.com/clarity-h2020/data-package/issues/17) from the Data Package, extract and parametrise the [EMIKAT API URL](https://github.com/clarity-h2020/emikat/issues/9) and show the two different Scenarios (Baseline / Future) for comparison.

**Comment by DenoBeno** [comment]
We don't have any adaptation scenarios yet, do we?

**Comment by p-a-s-c-a-l** [comment]
ATM here is no possibility to define adaptation scenarios, That's the next big step.
