### ISSUE TITLE
Scenario Analysis App is broken

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/scenario-analysis#15]
[Scenario Analysis App](https://csis.myclimateservice.eu/study/1/step/22/view/scenario-analysis) is broken, probably due to [changes in data model](https://github.com/clarity-h2020/docker-drupal/issues/93)?

The app logs the following error:

`node object is null or field "field_mcda_decision_strategy" is empty!'`

We should use a dev and live environment, instead of making changes to live environment directly.

**Comment by p-a-s-c-a-l** [comment]
@DenoBeno Please restore the default values for `field_mcda_decision_strategy`. I don't want to touch the Scenario Analysis App now because there are plenty of issues with the Map Component which have higher priority.

**Comment by DenoBeno** [comment]
Where are you getting this error? The field still exists and it has a default value as before. I didn't change this.

**Comment by DenoBeno** [comment]
As already commented - no changes in the data model from my side. No changes that I'm aware of. I can't help here, sorry - getting myself out of the loop.

**Comment by p-a-s-c-a-l** [comment]
@humerh @bernhardsk 
Did you change the format of the [RA/IA API API](https://github.com/clarity-h2020/emikat/issues/9)?

**Comment by p-a-s-c-a-l** [comment]
Putting this on-hold. ATM I don't want to touch [Scenario Analysis](https://github.com/clarity-h2020/scenario-analysis/) component, since I expect more changes in the near future.

**Comment by p-a-s-c-a-l** [comment]
done
