### ISSUE TITLE
Disable Criteria Function and Decision Strategy 

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/scenario-analysis#21]
Remove Criteria function & Decision strategy from user interface. 
Reason: YAGNI.

**Comment by p-a-s-c-a-l** [comment]
@therter I've modifed the app and removed some parts of it. Now the include in report functionality is broken. E.g. the "Include Chart in Report" Button produces the following screenshot:

![grafik](https://user-images.githubusercontent.com/1788226/83035132-5fdb2980-a039-11ea-9052-742951a640b6.png)

How is the chart DIV selected in the iFrame? By its position?! I've added the element ids `indicatorCriteriaTable` and `indicatorBarCharts`.

BTW, the generated screenshots are wrongly labelled with `map-...`

**Comment by therter** [comment]
> How is the chart DIV selected in the iFrame? By its position?! I've added the element ids `indicatorCriteriaTable` and `indicatorBarCharts`.

The divs are selected by their ids. The id for the table is indicatorCriteriaTable and the id for the charts is indicator-bar-charts

**Comment by p-a-s-c-a-l** [comment]
@therter O.K. and why is the resolution so low (max. 650x650px)?

![xxx](https://csis.myclimateservice.eu/sites/default/files/styles/max_650x650/public/report-images/2020-05/map-snapshot_127.jpg)

**Comment by p-a-s-c-a-l** [comment]
@therter 
> @therter O.K. problem was that I've _hidden_ the other nodes from DOM instead of removing them. Now it works.
> 
> But why is the resolution so low (max. 650x650px)?

**Comment by therter** [comment]
> But why is the resolution so low (max. 650x650px)?

The screenshot should have the same resolution as the image in the browser. 
When a screenshot of the map is made, the resolution will be increased by html2canvas. But this is not possible for the scenario analyses tool, because a wrong part of the scenario analyses tool will be shown, if I increase the resolution and I don't know why.
