### ISSUE TITLE
Scenario analysis only shows part of the scenarios

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/scenario-analysis#22]
On https://csis.myclimateservice.eu/study/25/step/3685/view/scenario-analysis, it's showing just one RCP45 and no RCP85 scenarios.

![image](https://user-images.githubusercontent.com/2961790/78304018-248f1380-753e-11ea-925e-2d052f10c036.png)

**Comment by p-a-s-c-a-l** [comment]
Yes, please see https://github.com/clarity-h2020/scenario-analysis/issues/19

**Comment by p-a-s-c-a-l** [comment]
O.K. now I understand what you man. That's a different Issue. We show only **5** indicators by default:

![indicators](https://user-images.githubusercontent.com/1788226/78645879-7de9a080-78b8-11ea-908f-84d3232e43ea.gif)

I agree. This is an interoperability issue. Kind of a "hidden feature". So we could expand the indicators table by default.
