### ISSUE TITLE
Combined Heat and Flood Impact Indicators

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/scenario-analysis#24]
Show different indicators both for heat and flood impact based on aggregated [Combined Heat and Flood Views](https://github.com/clarity-h2020/emikat/issues/46).

**Comment by p-a-s-c-a-l** [comment]
ATM, the following indicators are available:
- "EXPOSEDQUANTITY",
- "DAMAGEQUANTITY",
- "DISCOMFORT_LEVEL",
- "HEAT_WAVE_IMPACT",
- "COST_DEVELOPMENT",
- "COST_MAINTENANCE",
- "COST_RETROFITTING",

**Comment by p-a-s-c-a-l** [comment]
See https://github.com/clarity-h2020/csis/issues/177#issuecomment-665071953

**Comment by p-a-s-c-a-l** [comment]
Now with pluvial flood:

![image](https://user-images.githubusercontent.com/1788226/88678018-495f5600-d0ee-11ea-9a3e-5a43e780710f.png)

[Example Study 25](https://csis-dev.myclimateservice.eu/study/25/step/5110/view/scenario-analysis) on CSIS DEV.

**Comment by p-a-s-c-a-l** [comment]
New Indicators became available:


ID | COLUMNNAME
--|--
0 | "STUDY_VARIANT"
1 | "TIME_PERIOD"
2 | "EMISSIONS_SCENARIO"
3 | "EVENT_FREQUENCY"
4 | "SZM_SZENARIO_REF"
5 | "HW_EXPOSEDQUANTITY"
6 | "HW_DAMAGEQUANTITY"
7 | "HW_DISCOMFORT_LEVEL"
8 | "HW_HEAT_WAVE_IMPACT"
9 | "HW_ECO_IMPACT_DIRECT"
10 | "HW_ECO_IMPACT_INDIRECT"
11 | "HW_ECO_IMPACT_LIFE"
12 | "AO_COST_DEVELOPMENT"
13 | "AO_COST_MAINTENANCE"
14 | "AO_COST_RETROFITTING"
15 | "PF_FLOOD_IMPACT_EURO"
16 | "PF_ECO_IMPACT_RESIDENTAL_BLDG"
17 | "PF_ECO_IMPACT_NONRESIDENT_BLDG"
18 | "PF_ECO_IMPACT_ROAD"
19 | "PF_DAMAGEPROBABILITY"
20 | "PF_DAMAGE_CLASS"

**Comment by p-a-s-c-a-l** [comment]
According to @mattia-leone's [comments](https://github.com/clarity-h2020/csis/issues/154#issuecomment-669331990)

> The layers "heat damage probability" and "flood damage probability" I think can be removed, since they are not useful to end users

> in the table tab, I see that flood impacts in euro are separated (roads, res. buildings and non-res) so I guess they can be split also in the map, or not? 

So in the Scenario Analysis, we should ignore PF_DAMAGEPROBABILITY and include the detailed economic impact indicators in favour of the total ones.

@therter Beware! If @humerh changes the number and order of columns in the view, this might break the scenario  analysis application. So @therter has **always** to be notified by @humerh **before** such a change is made, otherwise scenario analysis in the [production system](https://csis.myclimateservice.eu/) might stop working.

**Comment by p-a-s-c-a-l** [comment]
done

**Comment by humerh** [comment]
Should the PF_DAMAGEPROBABILITY be removed by me definitely?
