### ISSUE TITLE
Impact Evaluation Visualisation

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/scenario-analysis#7]
Output of [impact modelling](//repository.atosresearch.eu/owncloud/remote.php/webdav/CLARITY/WP4%20Technology%20Support/T4.1%20CSIS%20Architecture/material/HC-LE%20Modelling%20Workflow/impact%20modelling%20heat%20wave.pptx) defined in https://github.com/clarity-h2020/csis/issues/21 and implemented in https://github.com/clarity-h2020/csis/issues/22 will look like

Hazards | Element at risk | Classes | Unit | D1 - D4
-- | -- | -- | -- | --
HW | Population | Age group 0-14 | pop./km2 | numeric value
HW | Population | Age group 15-64 | pop./km2 | numeric value
HW | Population | Age group >65 | pop./km2 | numeric value
FL | Population | Age group 0-14 | pop./km2 | numeric value
FL | Population | Age group 15-64 | pop./km2 | numeric value
FL | Population | Age group >65 | pop./km2 | numeric value
FL | Buildings | Continuous   Residential | m3/m2 | numeric value
FL | Buildings | Med-Hi Density   Discontinuous Res. | m3/m2 | numeric value
FL | Buildings | Low Density   Discontinuous Res. | m3/m2 | numeric value
FL | Buildings | Non Residential | m3/m2 | numeric value
FL | Infrastructure | Roads | ml (m2 ??) | numeric value
FL | Infrastructure | Railways | ml (m2 ??) | numeric value

![grafik](https://user-images.githubusercontent.com/1788226/48842673-21561600-ed95-11e8-98d0-df90de6cba57.png)

Example people damage classification:

![grafik](https://user-images.githubusercontent.com/1788226/48842709-3af75d80-ed95-11e8-8858-d3727a40a0e3.png)

The visualisation proposed in the  [current Mock-Ups](//repository.atosresearch.eu/owncloud/remote.php/webdav/CLARITY/WP1%20CO-Creation/T1.3%20Climate%20Services%20Co-Creation/CSIS%20Product%20Mockups/CSIS-Product-Master-v0.6.8.pdf) doesn't seem to be suitable:

![grafik](https://user-images.githubusercontent.com/1788226/48843152-8b22ef80-ed96-11e8-8aae-80b04daf2c29.png)
 
Instead of developing a new component for tabular visualisation of impact indicators, we *could* re-use the Scenario Analysis Component. However, the **JSON Data Format** (Example: [sampleIndicatorSet_1.json](https://github.com/clarity-h2020/scenario-analysis/blob/dev/samples/sampleIndicatorSet_1.json)) expected by this component doesn't support multidimensional tabular data. It just supports single indicators grouped into categories, so for example

- **Category**: HW Impact on Population (age group 0-14)
  - **Indicator**:  # of People with damage level D1
  - **Indicator**:  # of People with damage level D2
  - **Indicator**:  # of People with damage level D3
  - **Indicator**:  # of People with damage level D4
- **Category**: HW Impact on Population (age group 15-64)
  - **Indicator**:  # of People with damage level D1
  - **Indicator**:  # of People with damage level D2
  - **Indicator**:  # of People with damage level D3
  - **Indicator**:  # of People with damage level D4
- etc.

This supports a visualisation like this:

![grafik](https://user-images.githubusercontent.com/1788226/48843486-7d219e80-ed97-11e8-89b7-a49caa0877b0.png)

Furthermore, the scenario analysis component is intended to visualise **aggregated** Indicators for the **whole study area** (not a single grid cell), for a **single event** (e.g. the worst heat wave that might occur in the a specific period) but for **different scenarios**. 

> **Impact Scenario Analysis** 
> In probabilistic terms choosing in a deterministic way one or more significant events, among actually occurred past events or as a result of numerical hazard simulation models, shall be obtained as damage evaluation following a specific event.

Usually baseline vs. adaptation scenarios are compared but the scenario analysis component could also be used to compare different *Emission Scenarios*. So there is probably an additional step or service needed that **aggregates** the output of the impact model so that it can be visualised in the scenario analysis component.

**Comment by maesbri** [comment]
How is this related to each hazard index? 
In the image information is aggregrated by hazard type and classes of elements at risk but each hazard has several possible indexes (according to the hazard characterization screen). Or is it just that the different hazard indexes values are aggregated in a single value? if so, how is this aggregation calculated? I can imagine some hazard indexes may have more weight than others ... btw, this would also apply for the summary table we have in the hazard characterization (we have the Low, Medium, High per hazard index and the the total Low, Medium, High per Hazard type)

**Comment by p-a-s-c-a-l** [comment]
Those are the Heat related indexes provided by Science Support (for rcp26, rcp45, rcp85 and periods 1971 - 2000, 2011 - 2040, 2041 - 2070 and 2071 - 2100):

Climate   Index | Name | Description
-- | -- | --
CSU | Consecutive Summer Days | Number of   consecutive days per time period with daily maximum temperature above 25°C
Heat   Wave Duration | Hot period duration | Maximum number of consecutive   days when: i) Daily Tmax is above T1 for at least three days, ii) the average Tmax is above T1 over the entire period,   and iii) the daily Tmax must be above T2 every day of the period (the total heat wave period may be   longer than three days). T1 = 97.5th percentile, T2 = 81st percentile
Hot   days | Hot days > 75th percentile | Number of days per   year with a mean air temperature at 2 m above ground above the 75th percentile during   summer months (Apr-Sep)
HD | Hot days | number of days with daily   maximum  temperature above 30°C
SD | Summer days | number of days with daily   maximum  temperature above 25°C
TN | Tropical nights | number of days with daily   minimum temperature above 20°C
Tx90p | Percentage of days when Tmax   > 90th   percentile | percentage   of days per time period where daily maximum temperature is above the 90th percentile of daily   maximum temperatures of a five day window centred on each calendar day of a   given 30 year climate reference period

IMHO the relevant index for HW Impact Calculation is **Heat Wave Duration**, so those other Heat indexes shown in the HC / HC-LE Steps are just *"informative"* . But this has to be answered by @clarity-h2020/science-support-team and @clarity-h2020/mathematical-models-implementation-team.

In any case, the scenario-analysis component is mainly useful for comparison & ranking of different scenarios by means of indicators following to the [CRISMA](https://www.vtt.fi/inf/pdf/technology/2015/T228.pdf) definition of an indicator:

> In CRISMA, indicators illustrate World State aspects that are **representative for scenarios**. The indicators can either be represented by a single existing value in the CRISMA World State or are **aggregated by a function of several values** from the World State (e.g. average, minimum or maximum values in a given region for a given time).

So for (tabular) visualisation of the hazard indices, "raw" impact model output, etc. we probably need another component.

**Comment by claudiahahn** [comment]
Yes, for the HW impact calculation PLINIVS needs information about the duration of a heat wave. The other indices are informative. However, it might not be the heat wave duration index they are using but another index we have calculated specifically for PLINIVS (the number of consecutive days above a certain temperature threshold). Robert presented this index in his presentation in Madrid. We are hoping to have another telco with PLINIVS next week to discuss this index and see if they need anything else.

**Comment by p-a-s-c-a-l** [comment]
IMHO it depends on the individual Impact Model to decide which index is the relevant one. So a pragmatic solution would be to sent the complete Data Package Meta-Data (or just the URI) plus some context information like the study area polygon to the "Impact Model Service" (Emikat) (btw @bernhardsk, we need to set-up another repository for your scripts, etc.) and then let Impact Model Implementation to select **and retrieve** the HC(-LE), EE and VA data needed for the calculation. This makes especially sense if some of the data is stored either in or "nearby" (e.g. directly accessible PostgreSQL RDBMS container) the "Impact Model Service" instance so that data retrieval and extraction is performed only "locally".

@clarity-h2020/mathematical-models-implementation-team : WDYT?

**Comment by p-a-s-c-a-l** [comment]
@clarity-h2020/mathematical-models-implementation-team [Here](https://github.com/clarity-h2020/csis/issues/22#issuecomment-442460125) is an example that better explains the [comment above](https://github.com/clarity-h2020/scenario-analysis/issues/7#issuecomment-441642798).

**Comment by p-a-s-c-a-l** [comment]
We provide a [separate component](https://github.com/clarity-h2020/table-components/issues/4) for Impact Evaluation Visualisation. The Scenario Analysis Component will be used to visualise aggregated indicators.

![grafik](https://user-images.githubusercontent.com/1788226/50208171-c94d0800-0370-11e9-8cee-96eb4e2a2596.png)
